### ISSUE TITLE
Documentation shows screenshots of old dashboard

### ISSUE THREAD

**Issue by borpin** [OctopusDeploy/docs#1074]
https://github.com/OctopusDeploy/docs/blob/master/docs/octopus-rest-api/how-to-create-an-api-key.md

This shows the old Octopus Dashboard.

Can this be updated please.

**Comment by wordlee** [comment]
Thanks for reporting. I've updated the procedure. In this instance, I removed the screenshots but made sure the instructions are as clear as possible.
