### ISSUE TITLE
Excel Spreadsheet template is missing

### ISSUE THREAD

**Issue by ammaroff** [OctopusDeploy/docs#13]
Following the steps in [reporting getting started](https://github.com/OctopusDeploy/docs/blob/master/docs/administration/reporting.md#getting-started-reporting-gettingstarted)

`First, **[download the template](/docs/attachments/download the template)** and open it in Excel.`

The link is directing to missing/not found 404

**Comment by johnsimons** [comment]
I'll fix that soon.

For now [download it from here](https://github.com/OctopusDeploy/docs/raw/master/docs/attachments/OctopusReport.xlsx)

**Comment by johnsimons** [comment]
Fixed, thanks for reporting it.
