### ISSUE TITLE
"Create OctoPack" documentation is missing some information about NuSpec file naming

### ISSUE THREAD

**Issue by ericsampson** [OctopusDeploy/docs#1320]
The documentation on [Create Octopack > Adding a NuSpec file](https://octopus.com/docs/packaging-applications/create-packages/octopack#UsingOctoPack-AddingaNuSpec) makes it sound like the NuSpec file will always get picked up as long as it has the same name as the project file. I've found that this isn't true; setting the `OctoPackProjectName` MSBuild param will also change the behavior so that it looks for a NuSpec with that name instead of the project name.

Also, this part of the documentation should have information on the `OctoPackNuSpecFileName` MSBuild param, which is how you can resolve the above. I only found information about that param on a [forum post](https://help.octopus.com/t/teamcity-octopus-selecting-the-nuspec-file-per-environment/11481)

Thanks!!

**Comment by harrisonmeister** [comment]
Hi @ericsampson 

Thanks for your feedback!

I've gone ahead and drafted a Pull request for the documentation here - https://github.com/OctopusDeploy/docs/pull/1321

if you have time, it'd be great to see if the update matches your expectations.

Best regards,
Mark

**Comment by ericsampson** [comment]
Thank you @harrisonmeister that's awesome :)

The other thing that I had to figure out in order to make my scenario work is that I had to set the nuspec <id> param using a templated Octo MSBuild param. The scenario was "nuspec file exists but the generated Octo package name has to be different than the nuspec filename". Maybe this would be useful to cover somehow? The section on Nuget replacement tokens covers the mechanism, so I figured it out after a bit of experimentation with our build system.

Thanks again for the quick update, I hope it helps someone else :)

![image](https://user-images.githubusercontent.com/1183853/126372332-692d281e-260d-4067-86a0-a46050a4ac8d.png)
![image](https://user-images.githubusercontent.com/1183853/126372515-7b372fe7-4282-495e-9239-29516cd865fd.png)

**Comment by harrisonmeister** [comment]
> Thank you @harrisonmeister that's awesome :)
> 
> The other thing that I had to figure out in order to make my scenario work is that I had to set the nuspec param using a templated Octo MSBuild param. The scenario was "nuspec file exists but the generated Octo package name has to be different than the nuspec filename". Maybe this would be useful to cover somehow? The section on Nuget replacement tokens covers the mechanism, so I figured it out after a bit of experimentation with our build system.

I could add a sentence under the example nuspec file like this:

---

If you have an existing `.nuspec` file but you want the generated Octopus package name to be different from the `.nuspec` filename, you can use [NuGet replacement tokens](https://octopus.com/docs/packaging-applications/create-packages/octopack#nuget-replacement-tokens). For example, the `id` property in the `.nuspec` could be set as follows:

```xml
<id>$packageId</id>
```
Then you would pass the package id you wanted as part of the `OctoPackNuGetProperties` MSBuild parameter :

```text
/p:OctoPackNuGetProperties=packageid=YOUR-PACKAGE-ID
```

replacing `YOUR-PACKAGE-ID` with the id for your package.

**Comment by ericsampson** [comment]
Sounds great. Thanks for doing this work!!
