### ISSUE TITLE
Documentation for old versions

### ISSUE THREAD

**Issue by codeape2** [OctopusDeploy/docs#152]
Online (https://octopus.com/docs/) I only find documentation for versions down to 3.6. On our infrastructure, we are running version 3.4. Is the old documentation available somewhere?

**Comment by droyad** [comment]
@codeape2 Unfortunately we only started versioning docs with the `3.6` release. 

However the majority of the documentation should be the same with the exception of Subscriptions, Docker and Authentication providers. See what [has changed between 3.4 and 3.6](https://octopus.com/downloads/compare?from=3.4.0&to=3.6.0).

If you run into any trouble, contact us at `support@octopus.com`

**Comment by codeape2** [comment]
Ok thanks.

5. des. 2017 22:34 skrev "Robert Wagner" <notifications@github.com>:
