### ISSUE TITLE
Package deployment feature ordering -- Windows Service is missing

### ISSUE THREAD

**Issue by andreycha** [OctopusDeploy/docs#1593]
Hi,

There is a document which describes feature ordering for package deployment:
https://github.com/OctopusDeploy/docs/blob/05a6393f428ecbdcf0dc5693f4df03f20af07cf3/docs/deployments/packages/package-deployment-feature-ordering.md

However, it's doesn't mention "Windows Service" feature, so it's not clear at which point windows service stop and configuration occurs.

**Comment by harrisonmeister** [comment]
Hi @andreycha 

The service stop / start order is described on the windows services page [here](https://octopus.com/docs/deployments/windows/windows-services#WindowsServices-HowdoesOctopusactuallydeploymyWindowsService?)

It makes use of two files:

- [Octopus.Features.WindowsService_AfterPreDeploy.ps1](https://github.com/OctopusDeploy/Calamari/blob/master/source/Calamari/Scripts/Octopus.Features.WindowsService_AfterPreDeploy.ps1)
- [Octopus.Features.WindowsService_BeforePostDeploy.ps1](https://github.com/OctopusDeploy/Calamari/blob/master/source/Calamari/Scripts/Octopus.Features.WindowsService_BeforePostDeploy.ps1)

So looking at the feature ordering page you mentioned, that would be steps 1 and 3, respectively.

I hope that helps!

**Comment by harrisonmeister** [comment]
> 

Sorry, you are correct, steps 3 and 14. The package deployment feature ordering page is intended to be generic. This is why we don't explicitly call out windows services on the page. If we did, we'd also have to include every other deployment type too.

**Comment by andreycha** [comment]
Got it, thanks!
