### ISSUE TITLE
Contradictory and confusing detail in 'Creating releases' page

### ISSUE THREAD

**Issue by laingsimon** [OctopusDeploy/docs#18]
See page: https://octopus.com/docs/api-and-integration/octo.exe-command-line/creating-releases

This page has lead to some confusion and a fair bit of lost effort and time, there are 2 issues.

1. The [options] section states that switches are provided in `--SWITCH=VALUE` when the examples describe `--SWITCH _space_ VALUE`
2. The [options] section states that the --package switch can override the "Version number to use for a package in the release" however it overrides the package for a **STEP** in the release process.

The former issue certainly added some confusion as I was unsure as to whether iI was passing the switches to octo.exe correctly, however the latter issue is by far the most obscure and confusing.

Please can the documentation be clarified to prevent further confusion by people using octo.exe, including your support staff (see http://help.octopusdeploy.com/discussions/questions/7042-defaultpackageversion-package).

Also is it possible to explain/describe the reasons for why the "name of the step" needs to be specified; when it could reference a step which has nothing todo with deploying packages (e.g. a custom deployment step). When creating a release through the UI you select the **packages** not the packages for each step, hence the confusion here.

**Comment by NickJosevski** [comment]
@laingsimon Thank you for your feedback, sorry the documentation isn't clear and it caused you some confusion and frustration.

I've updated the documentation to be a bit more clear, those changes will be live sometime soon.

**Comment by laingsimon** [comment]
Thanks for changing this documentation. I can see that the changes will help to clarify the usage somewhat.

Can I suggest that the confusion between spaces and = are resolved at the same time.
