### ISSUE TITLE
Document progress service message

### ISSUE THREAD

**Issue by jenrik** [OctopusDeploy/docs#1949]
The ["Logging messages from scripts"](https://github.com/OctopusDeploy/docs/blob/main/src/pages/docs/deployments/custom-scripts/logging-messages-in-scripts.md) document only documents the raw format for setting the log level of messages, but is missing the documentation for setting the progress level when not using any undocumented language.

**Comment by steve-fenton-octopus** [comment]
Hi @jenrik are you able to give me some background about what you're trying to and what you'd like to see added?
