### ISSUE TITLE
Dark Mode?

### ISSUE THREAD

**Issue by antmeehan** [OctopusDeploy/docs#2129]
Any chance dark mode support is on the radar for the documentation site? So bright 😎

**Comment by steve-fenton-octopus** [comment]
Hello @antmeehan 

Yes, this is on our plan. We have a set of design updates coming that includes a dark mode based on your preference.

Hopefully you won't need the sunglasses too much longer.

Thanks,
Steve

**Comment by antmeehan** [comment]
Thanks @steve-fenton-octopus. Looking forward to it.

**Comment by steve-fenton-octopus** [comment]
Additional note for code blocks.

We introduced a light/dark mode for code blocks. When we implement dark mode it would good to update this to use a separate Shiki theme for each one using [dual themes](https://shiki.style/guide/dual-themes).

The interim version uses calculated values: https://github.com/OctopusDeploy/docs/pull/2147

**Comment by steve-fenton-octopus** [comment]
Also see #2258 

Dark mode is on its way, including user-preference detection and a toggle.

**Comment by steve-fenton-octopus** [comment]
@antmeehan we now have light and dark modes available. Let me know what you think.

![Docs site in light mode](https://github.com/OctopusDeploy/docs/assets/99181436/fdab8b60-032a-4c86-a3c9-4584c622de52)

![Docs site in dark mode](https://github.com/OctopusDeploy/docs/assets/99181436/61c0509c-9966-4e59-901a-d2d70f640e96)

**Comment by antmeehan** [comment]
Great work! Looks good. One comment so far is that the font on the code examples is a little hard to read:

![2024_05_07_21_09_09_Clipboard](https://github.com/OctopusDeploy/docs/assets/9822503/15df4d80-c40a-4ead-9dce-d6414743f8c3)

**Comment by steve-fenton-octopus** [comment]
Thanks @antmeehan - We'll take a look at this and tune it up.

What browser are you using?

**Comment by antmeehan** [comment]
Google Chrome on Windows 11. Dev Tools says its Consolas:

![image](https://github.com/OctopusDeploy/docs/assets/9822503/3fe781f3-006d-4f42-8855-b5b602de292f)

**Comment by steve-fenton-octopus** [comment]
@antmeehan the code font should be better now! Let me know if you still see any issues.
