### ISSUE TITLE
Deployment excel template link returning 404 in Production

### ISSUE THREAD

**Issue by hnrkndrssn** [OctopusDeploy/docs#2178]
We have a link to an [Excel template](https://octopus.com/docs/attachments/octopusreport.xlsx) on one of our [reporting pages](https://octopus.com/docs/administration/reporting/report-on-deployments-excel-template) that is returning a 404. 

I've tested the link when running the docs site locally and it works.

I can see the file being copied to the output folder when building the docs so I'm not sure what is different when the site is running in Production versus running locally.

**Comment by steve-fenton-octopus** [comment]
Thanks @hnrkndrssn 

There's a FWLB rule that was preventing this from working.

I've updated this and the download now works.
