### ISSUE TITLE
 Deploy to a Kubernetes cluster docs are out of date

### ISSUE THREAD

**Issue by jbristowe** [OctopusDeploy/docs#2217]
The page, [Deploy to a Kubernetes cluster](https://octopus.com/docs/deployments/kubernetes/deploy-container) is outdated and does not reflect the current state of Octopus. This page needs to be updated to reflect the change made to the step name and its behaviour. The step name is now `Configure and apply Kubernetes resources`.

**Comment by steve-fenton-octopus** [comment]
I believe we're all set with this now as the Kubernetes section has been refreshed!

https://docs.google.com/document/d/1VyjxapKiCDTUYSwWHWNokp-e-9tBF8CGxltC9tmg1Ok/edit?usp=sharing
