### ISSUE TITLE
Upload artifact to existing deployment includes headers in file content

### ISSUE THREAD

**Issue by szogun1987** [OctopusDeploy/docs#2399]
I have converted [this article](https://octopus.com/docs/octopus-rest-api/examples/artifacts/create-and-upload-artifacts) to use curl: 

```
# Upload file content
curl -v -X PUT -F fileData=@report.html -H "X-Octopus-ApiKey: ${OCTOPUS_API_KEY}" "${uploadUrl}"
```

Unfortunatelly it includes http part data:
```
--------------------------246875bc4e54cce7
Content-Disposition: form-data; name="fileData"; filename="report.html"
Content-Type: text/html

<!DOCTYPE html>
<html lang="en">
```
This is big issue for binary files, I can live with it for text ones.

Probably it is issue with octopus itself not with documentation so please move this issue to the right place.

**Comment by steve-fenton-octopus** [comment]
Hi @szogun1987 

Can you try using the `--data-binary` flag to see if it resolves your issue?

```
curl -v \
  -X PUT \
  --data-binary @report.html \
  -H "X-Octopus-ApiKey: ${OCTOPUS_API_KEY}" \
  "${uploadUrl}"
```

**Comment by szogun1987** [comment]
Thank you @steve-fenton-octopus  now there is no extra initial bytes. But content is truncated.
HTML was only example I upload tar.gz file with screenshots

**Comment by steve-fenton-octopus** [comment]
Hi @szogun1987 

I've asked our R&D team to take a look at this one. I'll let you know the outcome as soon I hear.
