### ISSUE TITLE
TeamCity API integration documentation lacks referenced videos

### ISSUE THREAD

**Issue by janv8000** [OctopusDeploy/docs#94]
https://github.com/OctopusDeploy/docs/blob/d79e7ff0bc76403b8c1dc08ba1aa6c5ddd458116/docs/api-and-integration/teamcity.md

> The video below demonstrates how to do this.

> The video below is from a webinar hosted by JetBrains in which we demonstrated these features:

No videos are linked however

**Comment by johnsimons** [comment]
Fixed in https://github.com/OctopusDeploy/docs/commit/17fe03ae270a0b20f29b58d673d4160d182cc33a

Thanks @janv8000 for reporting this.
